trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  testAssemblyPattern: '**\bin\$(buildConfiguration)\**\*Tests.dll'
  testResultsPattern: '**\bin\$(buildConfiguration)\**\TestResults\*.xml'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  name: 'RunUnitTest'
  inputs:
    command: 'test'
    projects: '**/Tests.cs'
    configuration: '$(buildConfiguration)'
